### ISSUE TITLE
Not working on SDK 30

### ISSUE THREAD

**Issue by ali-imran** [alpbak/BoxedVerticalSeekBar#17]
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljunit/framework/Assert;
        at abak.tr.com.boxedverticalseekbar.BoxedVertical.init(BoxedVertical.java:136)
        at abak.tr.com.boxedverticalseekbar.BoxedVertical.<init>(BoxedVertical.java:105)
        	... 38 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "junit.framework.Assert" on path: DexPathList[[zip file "/data/app/~~95EQU6LLgq3EYOt3yBXX1Q==/com.silkyapps.maclock-dU2DoBl7bjofNJ7RM5VJxQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~95EQU6LLgq3EYOt3yBXX1Q==/com.silkyapps.maclock-dU2DoBl7bjofNJ7RM5VJxQ==/lib/arm64, /data/app/~~95EQU6LLgq3EYOt3yBXX1Q==/com.silkyapps.maclock-dU2DoBl7bjofNJ7RM5VJxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 40 more

**Comment by alpbak** [comment]
I don't think this has anything to do with the BoxedVerticalSeekBar
